### ISSUE TITLE
Not workerd owncloud 10.3.1

### ISSUE THREAD

**Issue by WellD0ne** [owncloud/user_external#17] opened 2019-11-18 14:29 UTC
Hello!
Authorization does not work. I tried it on my mail server. I tried on mail.ru and gmail.com! Does not work!

`{"reqId":"0qUQbhbmf7ujPSWJDrAM","level":3,"time":"2019-11-18T17:27:47+03:00","remoteAddr":"xxx.xxx.xxx.xxx","user":"--","app":"core","method":"POST","url":"\/index.php\/login?user=xxx%40gmail.com","message":"User backend OC_User_IMAP not found."}
{"reqId":"0qUQbhbmf7ujPSWJDrAM","level":2,"time":"2019-11-18T17:27:47+03:00","remoteAddr":"xxx.xxx.xxx.xxx","user":"--","app":"core","method":"POST","url":"\/index.php\/login?user=xxx%40gmail.com","message":"Login failed: 'xxx@gmail.com' (Remote IP: 'xxx.xxx.xxx.xxx')"}
{"reqId":"DiyElqlcO7ryTmqHmzD0","level":3,"time":"2019-11-18T17:27:47+03:00","remoteAddr":"xxx.xxx.xxx.xxx","user":"--","app":"core","method":"GET","url":"\/index.php\/login?user=xxx%40gmail.com","message":"User backend OC_User_IMAP not found."}
{"reqId":"LJuMHF1P6mXLQqAUEyWm","level":3,"time":"2019-11-18T17:27:47+03:00","remoteAddr":"xxx.xxx.xxx.xxx","user":"--","app":"core","method":"GET","url":"\/index.php\/core\/js\/oc.js?v=8ae89207bc65025ed1c56024b4faa9b7","message":"User backend OC_User_IMAP not found."}
{"reqId":"EEyvQGLpCI26Xd5Hmw04","level":3,"time":"2019-11-18T17:27:47+03:00","remoteAddr":"xxx.xxx.xxx.xxx","user":"--","app":"core","method":"GET","url":"\/cron.php","message":"User backend OC_User_IMAP not found."}
{"reqId":"HjICQVtB46PBNWu8zPR2","level":3,"time":"2019-11-18T17:27:47+03:00","remoteAddr":"xxx.xxx.xxx.xxx","user":"--","app":"core","method":"GET","url":"\/index.php\/cron","message":"User backend OC_User_IMAP not found."}`

**Comment by VicDeo** [comment] 2019-11-19 10:41
duplicate of https://github.com/owncloud/user_external/issues/17 

Fixed by https://github.com/owncloud/user_external/issues/9
Fix has been not released yet.

**Closed by VicDeo** 2019-11-19 10:41 UTC
